
#ifndef PROJET_TLA_TERMINAL_H
#define PROJET_TLA_TERMINAL_H

enum Terminal {
    PROGRAMME,
    ID,
    VAR,
    DEUXPOINTS,
    POINTVIRGULE,
    VIRGULE,
    INTEGER,
    FLOAT,
    CHAR,
    BEGIN,
    END,
    EGALE,
    IF,
    THEN,
    ELSE,
    DO,
    WHILE,
    FOR,
    PARENTHESEOUVRANTE,
    PARENTHESEFERMANTE,
    ACCOLADEOUVRANTE,
    ACCOLADEFERMANTE,
    OPREL,
    OPADD,
    OPMUL,
    READ,
    READLN,
    WRITE,
    WRITELN,
    NB,
    DOLLAR,
    POINT,
};

const char * const terminaux_tab[] = {
        [0]="programme",
        [1]="id",
        [2]="var",
        [3]=":",
        [4]=";",
        [5]=",",
        [6]="integer",
        [7]="float",
        [8]="char",
        [9]="begin",
        [10]="end",
        [11]="=",
        [12]="if",
        [13]="then",
        [14]="else",
        [15]="do",
        [16]="while",
        [17]="for",
        [18]="(",
        [19]=")",
        [20]="{",
        [21]="}",
        [22]="oprel",
        [23]="opadd",
        [24]="opmul",
        [25]="read",
        [26]="readln",
        [27]="write",
        [28]="writeln",
        [29]="nb",
        [30]="$",
        [31]=".",
};


#endif //PROJET_TLA_TERMINAL_H
